import io
import sys
import os
import pytest
import fitz
from fastapi.testclient import TestClient
from docx import Document

sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), "..")))
from main import app, CONVERTER_API_KEY

client = TestClient(app)
AUTH_HEADERS = {"X-API-Key": CONVERTER_API_KEY}


def create_sample_pdf(text: str, num_pages: int = 1) -> bytes:
    """Helper to generate a clean synthetic text-based PDF in memory."""
    doc = fitz.open()
    for i in range(num_pages):
        page = doc.new_page()
        # Insert text at top of each page
        page.insert_text((50, 72), f"Page {i + 1}\n{text}")
    buffer = io.BytesIO()
    doc.save(buffer)
    doc.close()
    return buffer.getvalue()


def create_blank_pdf(num_pages: int = 1) -> bytes:
    """Helper to generate a blank / scan-like PDF with no text."""
    doc = fitz.open()
    for _ in range(num_pages):
        doc.new_page()
    buffer = io.BytesIO()
    doc.save(buffer)
    doc.close()
    return buffer.getvalue()


def test_health_check():
    """Verify health check endpoint returns status ok without auth."""
    response = client.get("/health")
    assert response.status_code == 200
    assert response.json() == {"status": "ok"}


def test_missing_api_key():
    """Verify request without X-API-Key header returns 401."""
    pdf_bytes = create_sample_pdf("Sample text")
    response = client.post(
        "/convert",
        files={"file": ("test.pdf", pdf_bytes, "application/pdf")},
    )
    assert response.status_code == 401
    assert "Invalid or missing API key" in response.json()["detail"]


def test_invalid_api_key():
    """Verify request with wrong X-API-Key header returns 401."""
    pdf_bytes = create_sample_pdf("Sample text")
    response = client.post(
        "/convert",
        headers={"X-API-Key": "wrong-secret-token"},
        files={"file": ("test.pdf", pdf_bytes, "application/pdf")},
    )
    assert response.status_code == 401
    assert "Invalid or missing API key" in response.json()["detail"]


def test_fake_pdf_magic_bytes():
    """Verify file without %PDF magic bytes is rejected with 422."""
    fake_pdf = b"Hello world, this is a plain text file pretending to be a PDF"
    response = client.post(
        "/convert",
        headers=AUTH_HEADERS,
        files={"file": ("fake.pdf", fake_pdf, "application/pdf")},
    )
    assert response.status_code == 422
    assert "not a valid PDF document" in response.json()["detail"]


def test_scanned_pdf_rejection():
    """Verify PDF without extractable text is rejected with scan warning."""
    blank_pdf = create_blank_pdf(1)
    response = client.post(
        "/convert",
        headers=AUTH_HEADERS,
        files={"file": ("scan.pdf", blank_pdf, "application/pdf")},
    )
    assert response.status_code == 422
    assert "This PDF is a scan and has no selectable text" in response.json()["detail"]


def test_page_limit_exceeded():
    """Verify PDF exceeding 30 pages is rejected with 422."""
    oversized_pdf = create_sample_pdf("Multi-page practical assignment", num_pages=31)
    response = client.post(
        "/convert",
        headers=AUTH_HEADERS,
        files={"file": ("oversized.pdf", oversized_pdf, "application/pdf")},
    )
    assert response.status_code == 422
    assert "exceeds the maximum limit of 30 pages" in response.json()["detail"]


def test_oversized_file_limit():
    """Verify file exceeding 10 MB is rejected with 413."""
    # Prefix with %PDF to pass magic check then pad to 10MB + 1KB
    large_payload = b"%PDF-1.7\n" + b"A" * (10 * 1024 * 1024 + 1024)
    response = client.post(
        "/convert",
        headers=AUTH_HEADERS,
        files={"file": ("huge.pdf", large_payload, "application/pdf")},
    )
    assert response.status_code == 413
    assert "exceeds the 10 MB limit" in response.json()["detail"]


def test_valid_pdf_conversion():
    """Verify valid text-based PDF converts into a readable Word .docx."""
    assignment_text = (
        "BCS Python Practical Assignment 1\n"
        "Name: Jayesh Prashant Ghagare\n"
        "Roll No: 24BCS042\n"
        "Batch: P1\n"
        "Code Implementation:\n"
        "def greet():\n"
        "    print('Hello AssignVault')\n"
    )
    pdf_bytes = create_sample_pdf(assignment_text, num_pages=1)

    response = client.post(
        "/convert",
        headers=AUTH_HEADERS,
        files={"file": ("assignment.pdf", pdf_bytes, "application/pdf")},
    )

    assert response.status_code == 200
    assert "application/vnd.openxmlformats-officedocument.wordprocessingml.document" in response.headers["content-type"]
    assert "converted.docx" in response.headers["content-disposition"]

    docx_bytes = response.content
    assert len(docx_bytes) > 0

    # Verify that the generated bytes open as a valid python-docx Document
    doc = Document(io.BytesIO(docx_bytes))
    full_text = " ".join(p.text for p in doc.paragraphs)
    assert "Jayesh" in full_text
    assert "24BCS042" in full_text
